development:
  adapter: postgresql
  encoding: unicode
  database: olfaction_development
  pool: 5
  username: craigsheen
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: olfaction_test
  pool: 5
  username: craigsheen
  password:
